services:
  api:
    build: ./apps/api
    ports:
      - "3000:3000"
    env_file:
      - ./apps/api/.env.development
    volumes:
      - ./apps/api/src:/app/src

  web:
    build: ./apps/web
    ports:
      - "65432:65432"
    env_file:
      - ./apps/web/.env.development
    volumes:
      - ./apps/web:/app
      - /app/node_modules
